version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - sica_network
    environment:
      - DB_HOST=database

  database:
    build:
        context: .
        dockerfile: bd-Dockerfile
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - sica_network

networks:
  sica_network:
